import Head from 'next/head'
import Layout from '../components/Layout'
import AnimatedText from '../components/AnimatedText'
import profilepic from '../../public/images/profile/developer-pic-1.png'
import Link from 'next/link'
import Image from 'next/image'
import Project1 from '../../public/images/projects/crypto-screener-cover-image.jpg'
const Projects = () => {
    const FeatureProject = ({ type, title, summary, image, link, githublink }) => {

        return (
            <article>
                <Link href={link || ""} className="">
                    <Image src={image || profilepic} alt="user git account "
                        className="w-full objective-fit h-auto" />
                </Link>
                <div>
                    <span className="">


                    </span>
                </div>
            </article>
        )
    }



    return (
        <>

            <Head>
                <title>Project created so far </title>
                <meta name="description" content="Generated by create next app" />

            </Head>
            <main className=" w-full  flex flex-col items-center justify-center mb-16">


                <Layout className="!pt-16 ">
                    <AnimatedText text="Imaging Trumps Knowledges"
                        className="!text-3xl !mb-12 md:!text-4xl lg:!text-6xl md:text-left"
                    />
                    {/* <div className="grid grid-col-12 gap-24">

                        <div className="col-span-12">
                            <FeatureProject
                                title={"Crypto Screener Application"}
                                summary={`A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency`}
                                link="/"
                                type="feature project"
                                image={Project1}

                            />
                        </div>
                        <div className="col-span-6 ">
                            Project one here

                        </div>
                        <div className="col-span-6">
                            project two here

                        </div>
                        <div className="col-span-12">
                            FeatureProject 0here

                        </div>
                        <div className="col-span-6">
                            project here
                        </div>
                        <div className="col-span-6">
                            project here
                        </div>

                    </div> */}

                    <div className="bg-light relative z-10">
                        <div className="relative px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
                            <div className="absolute inset-x-0 top-0 items-center justify-center hidden overflow-hidden md:flex md:inset-y-0">
                                <svg
                                    viewBox="0 0 88 88"
                                    className="w-full max-w-screen-xl text-gray-800"
                                >
                                    <circle
                                        fill="currentColor"
                                        fillOpacity="0.4"
                                        cx="44"
                                        cy="44"
                                        r="15.5"
                                    />
                                    <circle
                                        fillOpacity="0.1"
                                        fill="currentColor"
                                        cx="44"
                                        cy="44"
                                        r="44"
                                    />
                                    <circle
                                        fillOpacity="0.1"
                                        fill="currentColor"
                                        cx="44"
                                        cy="44"
                                        r="37.5"
                                    />
                                    <circle
                                        fillOpacity="0.1"
                                        fill="currentColor"
                                        cx="44"
                                        cy="44"
                                        r="29.5"
                                    />
                                    <circle
                                        fillOpacity="0.1"
                                        fill="currentColor"
                                        cx="44"
                                        cy="44"
                                        r="22.5"
                                    />
                                </svg>
                            </div>
                            <div className="relative grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Sed ut perspiciatis unde omnis iste
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Well, the way they make shows is
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Some dont, become nothing again
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Pommy ipsum smeg head whizz morris
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Taking the mick middle class bog
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Sportacus andrew weatherall goose
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Semi beard cream bun disaster alpha
                                    </p>
                                </div>
                                <div className="px-10 py-20 text-center transition duration-300 transform bg-light text-dark rounded shadow-2xl hover:scale-105 md:shadow-xl hover:shadow-2xl">
                                    <p className="font-semibold text-dark">
                                        Bro ipsum dolor sit amet gaper dart
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </Layout>
            </main>

        </>
    )

}


export default Projects